-- 아이스크림 가게 상반기 주문 정보:FIRST_HALF
-- 아이스크림 성분에 대한 정보:ICECREAM_INFO
SELECT a.FLAVOR
FROM FIRST_HALF a 
JOIN ICECREAM_INFO b
ON a.FLAVOR = b.FLAVOR
WHERE a.TOTAL_ORDER > 3000 and b.INGREDIENT_TYPE = 'fruit_based'
ORDER BY a.TOTAL_ORDER DESC